/*--------------------------------*- C++ -*----------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  v2412                         |
|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/

#ifndef OFVersion_H
#define OFVersion_H

#define FOAM_VERSION 2412
#define FOAM_VERSION_STRING v2412

#endif // OFVersion_H
