#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Compile OpenFOAM libraries and applications based on version
if [ "$WM_PROJECT_VERSION" = "9" ] || [ "$WM_PROJECT_VERSION" = "10" ] || [ "$WM_PROJECT_VERSION" = "11" ] || [ "$WM_PROJECT_VERSION" = "12" ] || [ "$WM_PROJECT_VERSION" = "13" ]; then
    echo "  -> Error: OpenFOAM version $WM_PROJECT_VERSION is not supported"
    echo "  -> Supported versions are: v2406, v2412, v2506, v2512 and newer"
    exit 1
elif [ "$WM_PROJECT_VERSION" = "v2406" ] || [ "$WM_PROJECT_VERSION" = "v2412" ] || [ "$WM_PROJECT_VERSION" = "v2506" ] || [ "$WM_PROJECT_VERSION" = "v2512" ]; then
    echo "  -> Cleaning solvers for OpenFOAM $WM_PROJECT_VERSION"
    wclean ./unresolvedSpherePFPlus
    wclean ./unresolvedGrainPFPlus
    wclean ./resolvedSpherePFPlus
    wclean ./resolvedSphereVoFPFPlus
else
    echo "  -> Error: Unknown OpenFOAM version: $WM_PROJECT_VERSION"
    echo "  -> Cannot proceed with wclean"
    exit 1
fi




#------------------------------------------------------------------------------
