#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Compile OpenFOAM libraries and applications
# Check OpenFOAM version
echo "  -> detected OpenFOAM version: $WM_PROJECT_VERSION"

# Compile OpenFOAM libraries and applications based on version
if [ "$WM_PROJECT_VERSION" = "9" ]; then
    echo "  -> building solvers for OpenFOAM 9"
    wmake ./unresolvedSpherePFPlus/v9
    wmake ./legacy/unresolvedSpherePFPisoFoam/v9
    wmake ./legacy/unresolvedGrainPFPisoFoam/v9
elif [ "$WM_PROJECT_VERSION" = "v2406" ] || [ "$WM_PROJECT_VERSION" = "v2412" ]; then
    echo "  -> building solvers for OpenFOAM $WM_PROJECT_VERSION"
    wmake ./legacy/unresolvedSpherePFPisoFoam/v24
    wmake ./unresolvedSpherePFPlus/v24
    wmake ./unresolvedGrainPFPlus/v24
    wmake ./resolvedSpherePFPlus/v24
    wmake ./resolvedSphereVoFPFPlus/v24
else
    echo "  -> Error: Unknown OpenFOAM version: $WM_PROJECT_VERSION"
    echo "  -> Cannot proceed with build"
    exit 1
fi




#------------------------------------------------------------------------------
