#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

./version

# Compile libraries and applications
echo "\nCompiling phasicFlowCoupling library"
wmake ./phasicFlowCoupling 


echo "\nCompiling utilities"
utilities/wmake

echo "\nCompiling solvers"
solvers/wmake
#------------------------------------------------------------------------------
