#!/bin/sh
set -e  # Exit immediately if a command exits with a non-zero status
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
# First run OpenFoam Aplication

echo "\n<--------------------------------------------------------------------->"
echo "1) fluent3DMeshToFoam"
echo "<--------------------------------------------------------------------->\n"
fluent3DMeshToFoam conduit.msh

echo "\n<--------------------------------------------------------------------->"
echo "2) Running Step 1 (0-2 DEM) "
echo "<--------------------------------------------------------------------->\n"

echo " 2.1) add Particle "
particlesPhasicFlow
echo " 2.2) add Geometry "
geometryPhasicFlow
echo " 2.3) Running "


echo "\n<--------------------------------------------------------------------->"
echo "3) Copy Orginal Data to 2s (P , U , Alpha ) "
echo "<--------------------------------------------------------------------->\n"
cp ./FluidField/* ./0

echo "\n<--------------------------------------------------------------------->"
echo "3) Running Step 2 (2-10 CFD-DEM) "
echo "<--------------------------------------------------------------------->\n"
unresolvedSpherePFPlus


echo "\n<--------------------------------------------------------------------->"
echo "4) Making VTK File "
echo "<--------------------------------------------------------------------->\n"
pFlowToVTK
touch foam.foam
#------------------------------------------------------------------------------
