#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Creating inner mesh
cd inner
blockMesh
surfaceFeatureExtract
snappyHexMesh -overwrite
topoSet

# Creating outer mesh
cd ../outer
blockMesh
surfaceFeatureExtract
snappyHexMesh -overwrite

# Merging meshes together
mergeMeshes -overwrite . ../inner

# Setting AMI and wall patches
changeDictionary

# Copying the mesh to the main simulation 
cp -r constant/polyMesh ../../constant

cd ..

#------------------------------------------------------------------------------
