#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Using two cores for DEM simulations
export OMP_NUM_THREADS=2

# Source tutorial run functions
# First run OpenFoam Aplication

echo "\n<--------------------------------------------------------------------->"
echo "1) Generating the CFD mesh "
echo "<--------------------------------------------------------------------->\n"
cd mesh
./Allmesh
cd ..

echo "\n<--------------------------------------------------------------------->"
echo "2) Running Step 1 (0-4 DEM) "
echo "<--------------------------------------------------------------------->\n"

echo " 2.1) add Particle "
particlesPhasicFlow
echo " 2.2) add Geometry "
geometryPhasicFlow
echo " 2.3) Running "
sphereGranFlow


echo "\n<--------------------------------------------------------------------->"
echo "3) Copy Orginal Data to 4s (P , U , Alpha ) "
echo "<--------------------------------------------------------------------->\n"
cp ./FluidField/* ./4

echo "\n<--------------------------------------------------------------------->"
echo "3) Running Step 2 (4-10 CFD-DEM) "
echo "<--------------------------------------------------------------------->\n"

echo "3.1) Preparing for parallel processing "
decomposePar
echo "3.2) Running "
mpirun -np 4 resolvedSpherePFPlus -parallel
echo "3.3) Reconstructing "
reconstructParMesh
reconstructPar

echo "\n<--------------------------------------------------------------------->"
echo "4) Making VTK File "
echo "<--------------------------------------------------------------------->\n"
foamToVTK -time 4:10
pFlowToVTK -t 4:10

#------------------------------------------------------------------------------
