#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Using two cores for DEM simulations
export OMP_NUM_THREADS=2

# Source tutorial run functions
# First run OpenFoam Aplication

echo "\n<--------------------------------------------------------------------->"
echo "1) Running blockMesh"
echo "<--------------------------------------------------------------------->\n"
blockMesh

echo "\n<--------------------------------------------------------------------->"
echo "2) Running Step 1 (Locating the particle with rotational velocity) "
echo "<--------------------------------------------------------------------->\n"

echo " 2.1) add Particle "
particlesPhasicFlow
echo " 2.2) add Geometry "
geometryPhasicFlow

echo "\n<--------------------------------------------------------------------->"
echo "3) Running Step 2 (0-0.5 CFD-DEM) "
echo "<--------------------------------------------------------------------->\n"

echo "3.1) Copy Orginal Data to 0s (P_rgh , U , alpha, IBVolFraction, alpha.water) "
cp ./FluidField/* ./0
echo "3.2) Running setFields to set water field"
setFields
echo "3.3) Running "
decomposePar
mpirun -np 4 resolvedSphereVoFPFPlus -parallel
reconstructParMesh
reconstructPar

echo "\n<--------------------------------------------------------------------->"
echo "4) Making VTK File "
echo "<--------------------------------------------------------------------->\n"
foamToVTK -time 0:0.5
pFlowToVTK -t 0:0.5

#------------------------------------------------------------------------------
