#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Using two cores for DEM simulations
export OMP_NUM_THREADS=2

# Source tutorial run functions
# First run OpenFoam Aplication

echo "\n<--------------------------------------------------------------------->"
echo "1) Running blockMesh"
echo "<--------------------------------------------------------------------->\n"
blockMesh

echo "\n<--------------------------------------------------------------------->"
echo "2) Running Step 1 (Locating the particle: 0-2 DEM) "
echo "<--------------------------------------------------------------------->\n"

echo " 2.1) add Particle "
particlesPhasicFlow
echo " 2.2) add Geometry "
geometryPhasicFlow
echo " 2.3) Running DEM "
sphereGranFlow

echo "\n<--------------------------------------------------------------------->"
echo "3) Running Step 2 (2-4 CFD-DEM) "
echo "<--------------------------------------------------------------------->\n"

echo "3.1) Copy Orginal Data to 0s (P_rgh , U , voidFraction, IBVolFraction, alpha.water) "
cp ./FluidField/* ./2
echo "3.2) Running setFields to set water field"
setFields
echo "3.3) Running "
decomposePar
mpirun -np 8 resolvedSphereVoFPFPlus -parallel
reconstructParMesh
reconstructPar

echo "\n<--------------------------------------------------------------------->"
echo "4) Making VTK File "
echo "<--------------------------------------------------------------------->\n"
foamToVTK -time 2:4
pFlowToVTK -t 2:4

#------------------------------------------------------------------------------
