#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
# First run OpenFoam Aplication

echo "\n<--------------------------------------------------------------------->"
echo "1) Running blockmesh"
echo "<--------------------------------------------------------------------->\n"
blockMesh

echo "\n<--------------------------------------------------------------------->"
echo "2) Running Step 1 (0-2 DEM) "
echo "<--------------------------------------------------------------------->\n"

echo " 2.1) add Particle "
particlesPhasicFlow
echo " 2.2) add Geometry "
geometryPhasicFlow
echo " 2.3) Running "
sphereGranFlow


echo "\n<--------------------------------------------------------------------->"
echo "3) Copy Orginal Data to 2s (P , U , Alpha ) "
echo "<--------------------------------------------------------------------->\n"
cp ./FluidField/alpha ./2
cp ./FluidField/p ./2
cp ./FluidField/U ./2

echo "\n<--------------------------------------------------------------------->"
echo "3) Running Step 2 (2-10 CFD-DEM) "
echo "<--------------------------------------------------------------------->\n"
unresolvedSpherePFPisoFoam

echo "\n<--------------------------------------------------------------------->"
echo "4) Making VTK File "
echo "<--------------------------------------------------------------------->\n"
foamToVTK -time 2:10
pFlowToVTK -t 2:10

#------------------------------------------------------------------------------
